
#### general settings

# name: 01_IRN_DB_x2_scratch_DIV2K
# name: 01_IRN_DB_scratch_5K_RAIN_PRINCESS_no_zloss_no_rec
# name: 01_IRN_DB_scratch_5K_RAIN_PRINCESS_no_zloss
# name: test_wmf_twoBranches_4_2
name: style_inv_10.20.2
use_tb_logger: False
model: IRN+
distortion: sr
scale: 1
gpu_ids: [0, 2, 5]
identity: True
compress_flag: True
# compress_mode: diffjpeg
# suffix: "predict"
#### datasets
 
datasets:
  train:
    name: train_style_transfer
    mode: ST
    # dataroot_GT: ~ # path to the original images
    # dataroot_LQ: ~ # path to the images after the operators 
    data_json_file: "/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/codes/data/dataset/ControlNet_ST_full/prompts.json"
    # "/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/codes/data/dataset/ControlNet_ST_full/prompts.json"
    # "/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/codes/data/dataset/ControlNet_ST/prompts.json" 
    #"/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/dataset/OmniEdit-Filtered-1.2M/prompts.json"
    resolution: 256
    # use_shuffle: true
    # use_shuffle: false 
    n_workers: 8  # per GPU
    batch_size: 8
    # GT_size: 144
    # use_flip: true ##
    # use_rot: true
    # color: RGB

  val:
    name: val_style_transfer
    mode: ST
    data_json_file: "/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/codes/data/dataset/ControlNet_ST/prompts.json" #"/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/dataset/OmniEdit-Filtered-1.2M/prompts.json"
    resolution: 256

  test:
    name: test_style_transfer
    mode: ST
    data_json_file: "/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/codes/data/dataset/ControlNet_ST/prompts.json" #"/home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/dataset/OmniEdit-Filtered-1.2M/prompts.json"
    resolution: 256

#### network structures

network_G:
  which_model_G:
      # subnet_type: CBAM
      subnet_type: ConvNet
      non_inv_block: "Identity" #"control_v11e_sd15_ip2p-finetuned"
  in_nc: 3
  out_nc: 3
  branch_type: single_branch
  block_num: [8, 8] #8
  scale: 1
  init: xavier


#### path

path:
  # pretrain_model_G: /disk1/ouyang/proj/invert_image_op/Invertible-Image-Rescaling/experiments/jpg_WMF_twoBranches_4_1/models/100000_G.pth 
  # pretrain_model_G: /home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/experiments/style_inv_archived_250927-194353/models/latest_G.pth

  strict_load: false
  # resume_state: /home/hesong/disk1/DF_INV/code/ControlNet-v1-1-nightly/inv_modules/IVOP/experiments/style_inv_archived_250927-194353/training_state/46100.state # "path to the .state file" or ~
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 50000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [10000, 20000, 30000, 40000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l2
  lpips_net: "vgg"
  manual_seed: 12345

  val_freq: !!float 100

  lambda_fit_forw: 1.
  lambda_rec_back: 4.
  lambda_ce_forw: 0.
  lambda_lpips_forw: 1.
  lambda_lpips_back: 0.
  lambda_ssim_forw: 0.
  lambda_ssim_back: 1.
  
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 100
